export default {
    Logo: require('../Assets/Images/logo.png'),
    GOOGLE: require('../Assets/Images/google.png'),
    EMAIL: require('../Assets/Images/email.png'),
    UNLOCK: require('../Assets/Images/unlock.png'),
    USER: require('../Assets/Images/user.png'),
    CALL: require('../Assets/Images/call.png'),
    MARKER: require('../Assets/Images/marker.png'),
    DOG: require('../Assets/Images/dog.png'),
    BURN: require('../Assets/Images/burn.png'),
    CAT: require('../Assets/Images/cat.png'),
    CHARGING: require('../Assets/Images/charging.png'),
    WIFI: require('../Assets/Images/wifi.png'),
    WIFINETWORK: require('../Assets/Images/wifinetwork.png'),
    CLOUDDOWNLOAD: require('../Assets/Images/cloud-download.png'),
    REFRESH: require('../Assets/Images/refresh.png'),
    REFRESHICON: require('../Assets/Images/refreshIcon.png'),
    PETAVATAR: require('../Assets/Images/petavatar.png'),
    PET: require('../Assets/Images/pet.png'),
    USERAVATAR: require('../Assets/Images/useravatar.png'),
    MENU: require('../Assets/Images/menu.png'),
    CALORIES: require('../Assets/Images/calories.png'),
    REST: require('../Assets/Images/rest.png'),
};